version: '2'

services:
  postgres:
    extends:
      file: docker-compose-common.yml
      service: postgres

  django:
    extends:
      file: docker-compose-common.yml
      service: dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    ports:
      - '8000:8000'

  nginx:
    extends:
      file: docker-compose-common.yml
      service: nginx
    build: ./compose/nginx/dev
    depends_on:
      - django
    ports:
      - "80:80"
