version: '2'

services:
  postgres:
    extends:
      file: docker-compose-common.yml
      service: postgres
    restart: always

  django:
    extends:
      file: docker-compose-common.yml
      service: prod
    command: uwsgi --emperor uwsgi.ini
    depends_on:
      - postgres

  nginx:
    extends:
      file: docker-compose-common.yml
      service: nginx
    build: ./compose/nginx/prod
    ports:
      - "80:80"
      - "443:443"
    restart: always
